[project]
name = "kryptonite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dill>=0.4.1",
    "from-root>=1.3.0",
    "scikit-learn>=1.8.0",
    "ultralytics>=8.4.12",
]
